### ISSUE TITLE
Error in Stacks Profile

### ISSUE THREAD

**Issue by schnello** [Ravenholdt-TC/SimcScripts#8]
Error Message:
Error: Unexpected parameter '345]'. Expected format: name=value

I guess the generated profile for the "AzeriteStack" is defect

Code Line:
`profileset."Synaptic Spark Capacitor_3"+=azerite_override=500:["PR", 345]/500:["PR", 345]/500:["PR", 345]`

[AzeriteStacks_1T_demortus.zip](https://github.com/Ravenholdt-TC/SimcScripts/files/2352423/AzeriteStacks_1T_demortus.zip)

Testet also with commit 9cc469d26ae86319dfd5e54520553a0693439838:
All ok and script execute all steps.

**Comment by Mystler** [comment]
Thanks for reporting that. Should be fixed in my latest commit now.
